services:
  ntfy:
    image: binwiederhier/ntfy:v2.17
    container_name: ntfy
    networks:
      - t3_proxy
    restart: always
#    ports:
#      - "80:80"
    volumes:
      - ./ntfy-data/cache:/var/cache/ntfy
      - ./ntfy-data/config:/etc/ntfy
    #command: "serve --cache-file /var/cache/ntfy/cache.db"
    command: serve
    environment:
      - TZ=America/New_York
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMAINNAME}`)"
      - "traefik.http.routers.ntfy.entrypoints=https"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"

networks:
  t3_proxy:
    external: true 
