services:

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    #ports:
    #  - "8081:80"
    networks:
    #  - default
      - t3_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tools.rule=Host(`tools.${DOMAINNAME}`)"
      - "traefik.http.routers.tools.entrypoints=https"
      - "traefik.http.routers.tools.tls=true"
      - "traefik.http.services.tools.loadbalancer.server.port=80"    

networks:
  default:
    driver: bridge


  t3_proxy:
    external: true